// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'verbs.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'verbs.g.dart';

@freezed
class Verbs with _$Verbs {
  const factory Verbs({
    required int id,
    required String fr,
    required String pastSimple,
    required String pastParticipe,
    required String infinitif,

  }) = _Verbs;

  factory Verbs.fromJson(Map<String, Object?> json)
  => _$VerbsFromJson(json);
}